config/routes.rb
Rails.application.routes.draw do
  resources :buggs
  # get 'bugs/index'
  # get 'bugs/show'
  # get 'bugs/edit'
  # get 'bugs/destroy'
  # get 'bugs/new'

  resources :bugs
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "/sessions#new"

  root :to => redirect("/projects")
  # devise_scope :user do

  #   root :to => "devise/registrations#new"

  # end

  # unauthenticated do
  #   root '/users/sign_up'
  # end

  # authenticated do
  #   root '/projects'
  #   # resources :things
  # end
end

app/models/bugg.rb
class Bugg < ApplicationRecord
  acts_as_paranoid
  validates :title, presence: true
  validates :status, presence: true
  validates :bugg_type, presence: true
  validates :project_id, presence: true
  mount_uploader :screenshot, AvatarUploader

  validates_uniqueness_of :title, scope: :project_id

  belongs_to :project, foreign_key: 'project_id'
  belongs_to :qa, class_name: "User", foreign_key: 'qa_id'
  belongs_to :solver, class_name: "User", foreign_key: 'solver_id', optional: true
end

app/controllers/buggs_controller.rb
class BuggsController < ApplicationController
  before_action :set_bugg, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /buggs or /buggs.json
  def index
    @pagy, @buggs = pagy(Bugg.where(qa_id: current_user.id), page: params[:page], items: 3)
  end

  # GET /buggs/1 or /buggs/1.json
  def show
    print '====================================================================='
  end

  # GET /buggs/new
  def new
    @bugg = Bugg.new
    @project = Project.find(params[:project_id])
  end

  # GET /buggs/1/edit
  def edit
  end

  # POST /buggs or /buggs.json
  def create
    @bugg = Bugg.new(bugg_params)
    @project = Project.find(bugg_params[:project_id].to_i)
    @bugg.project = @project
    @bugg.qa = current_user

    respond_to do |format|
      if @bugg.save
        format.html { redirect_to bugg_url(@bugg), notice: "Bugg was successfully created." }
        format.json { render :show, status: :created, location: @bugg }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bugg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buggs/1 or /buggs/1.json
  def update
    respond_to do |format|
      print '000000000000000000000000000000000000000000000000000000000000'

      print update_bugg_params[:status]
      print 'update_bugg_params[:solver_id]'
      print update_bugg_params

      if current_user.user_type == 1 && update_bugg_params[:status] == '2'
        print '1111111111111111111111111111111111111111111111111111111111111111111111111111'
        if @bugg.update(update_bugg_params)
          format.html { redirect_to bugg_url(@bugg), notice: "Bugg was successfully updated." }
          format.json { render :show, status: :ok, location: @bugg }
          format.js
        end

      elsif @bugg.update(bugg_params)
        format.html { redirect_to bugg_url(@bugg), notice: "Bugg was successfully updated." }
        format.json { render :show, status: :ok, location: @bugg }

        if current_user.user_type == 1
          print "tesssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssst  "

          print params.require(:bugg).permit(:status)[:status] == '2'
          print params.require(:bugg).permit(:status)[:status].class
          if params.require(:bugg).permit(:status)[:status] == '2'

            print "tesssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssst"
            # current_user.solved_buggs << @bugg
            # @bugg.update_attribute(:solver_id, current_user.id)
            # print(bugs)

          end
        end

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bugg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buggs/1 or /buggs/1.json
  def destroy
    @bugg.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Bugg was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bugg
    @bugg = Bugg.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bugg_params
    params.require(:bugg).permit(:title, :description, :bugg_type, :deadline, :status, :screenshot, :project_id)
  end

  def update_bugg_params
    params.require(:bugg).permit(:title, :description, :bugg_type, :deadline, :status, :screenshot, :project_id, :solver_id)
  end
end

app/helpers/buggs_helper.rb
module BuggsHelper
end

app/views/buggs/_bugg.html.erb
<div id="<%= dom_id bugg %>" class="container border border-info" style="background: #d2f7f7">


<p>
<strong>Title</strong>
<%= bugg.title  %>
</p>


<p>
<strong>description</strong>
<%= bugg.description  %>
</p>


<p>
<strong>Type</strong>
</p>

<% if bugg.bugg_type == 0  %>
    Bug
<% else %>
    Feature
<% end %>


<p>
<strong>status</strong>
</p>

<% if bugg.status == 0  %>
    New

    <% elsif bugg.status == 1 %>
    Started

    <% else %>
        <% if bugg.bugg_type == 1 %>
          Completed
        <% else %>
           Resolved
        <% end %>

<% end %>

<p>

<strong>Project</strong>
<%= bugg.project.name %>
</p>


<p>
<strong>Screenshot</strong>
<% if (bugg.screenshot.url) != nil  %>
<image src="<%= url_for(bugg.screenshot.url)%>" >
<% else %>
<p> No screenshot was attached </p>
<% end %>

</p>

</div>

app/views/buggs/_form.html.erb
<center>

<%= form_with(model: bugg, local: false, id: "form_id" ) do |form| %>
<%= @project %>

  <% if bugg.errors.any? %>
    <div style="color: red">
      <h5><%= pluralize(bugg.errors.count, "error") %> prohibited this bugg from being saved:</h5>

      <ul>
        <% bugg.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :tbugg_ype, style: "display: block" %>
    <%= form.number_field :bugg_type %>
  </div>

  <div>
      <%= form.label :screenshot, style: "display: block" %>
      <%= form.file_field :screenshot %>
    </div>

  <div>

  <% if project != nil %>

  <%= project %>

  <%= form.hidden_field :project_id, value: @project.id %>

  <% end %>

    <%= form.submit "Submit", class: "project-btn", id:"pro" %>
  </div>
<% end %>

</center>

app/views/buggs/edit.html.erb
<center>


<h1>Editing bugg</h1>





<% bugg = @bugg %>


<% if bugg.status != 2 %>

<%= form_with(model: bugg) do |form| %>
  
  <% if current_user.user_type == 2 %>
  
    <% if bugg.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(bugg.errors.count, "error") %> prohibited this bugg from being saved:</h2>
  
        <ul>
          <% bugg.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  

    <div>
    <strong>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
      </strong>
    </div>

    <div>
     <strong> <%= form.label :description, style: "display: block" %>
     </strong>
      <%= form.text_field :description %>
    </div>


    <div>
<strong>
      <%= form.label :bugg_type, style: "display: block" %>
      </strong>


      <div class="container row">

        <%= form.select :bugg_type, options_for_select([["Bug", 0], ["Feature", 1]])  %>
      
      </div>
    </div>




    <div>
    <strong>
    <%= form.label :screenshot, style: "display: block" %>
    </strong>
      <%= form.file_field :screenshot %>
    </div>
    
  
    <div>
  
    <% if @project != nil %>
  
   
  
    <%= form.hidden_field :project_id, value: @project.id %>
  
    <% end %>


    <% elsif current_user.user_type == 1 %>


    <div>

            <h3>  <%= bugg.bugg_type==0 ? "This is a Bug" : "This is a feature" %> </h3>

<strong>
      <%= form.label :status, style: "display: block" %>
</strong>
<% if bugg.bugg_type == 0 %>
    <% l_status = "Resolved" %>
  <% else %>
    <% l_status = "Completed" %>
  <% end %>

<div class="container row">

  <%= form.select :status, options_for_select([["New", 0], ["Started", 1], [l_status, 2]])  %>

</div>

     
    </div>
    

  <% end %>


  <%= form.hidden_field :solver_id, value: current_user.id  %>
      <%= form.submit %>
    </div>
  <% end %>
  

<br>







<br>

<div>

  <%= link_to "Show this bugg", @bugg, class: "btn btn-info" %> 

  <br>
  <br>


 
<% if current_user.user_type == 3 %>
<div>
<%= link_to "See all bugs", buggs_path, class: "btn btn-primary" %>

</div>
<% end %> 

</div>

<% else %>

<h2> Bug has been solved </h2>

<%= link_to "Back to home", projects_path, class: "btn btn-primary" %>
          <% end %>


</center>

app/views/buggs/index.html.erb
<center>

<p style="color: green"><%= notice %></p>

<h1>All Buggs created by You</h1>

<div id="buggs">

<% if @buggs.count != 0 %>

<div class="container" id="projects">
<table class="table table-light ">
  <% num = 0 %>
  <thead>
  <tr>
    <th scope="col">Sr. no.</th>
    <th scope="col">Title</th>
    <th scope="col">Type</th>
    <th scope="col">Status</th>
    
  </tr>
  </thead>
  <tbody>
  <% @buggs.each do |bugg| %>
  <tr>
    <th scope="row"> <%= num=num+1 %> </th>
    <td> <%= link_to bugg.title, bugg: bugg %> </td>

    <td>  
      <% if bugg.bugg_type == 0  %>
        Bug
      <% else %>
        Feature
      <% end %>
    </td>

    <td> 
    <% if bugg.status == 0  %>
    New

    <% elsif bugg.status == 1 %>
    Started

    <% else %>
        <% if bugg.bugg_type == 1 %>
          Completed
        <% else %>
          Resolved
        <% end %>

    <% end %>
    </td>
    
  </tr>
  <% end %>

  </tbody>
  </table>

   <center width= "100%" >
    <%== pagy_info(@pagy)%>
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
    </center> 

<% else %>
<p>No projects to show</p>
<% end %>

    <p>
      <%= link_to "Back to Home", projects_path, class: "btn btn-info" %>
    </p>

</div>

</center>

app/views/buggs/new.html.erb
<center>


<h1>New bugg</h1>

<% bugg = @bugg %>



<%= form_with(model: bugg) do |form| %>
  
  
    <% if bugg.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(bugg.errors.count, "error") %> prohibited this bugg from being saved:</h2>
  
        <ul>
          <% bugg.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  
    <div>
    <strong>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
      </strong>
    </div>

    <div>
     <strong> <%= form.label :description, style: "display: block" %>
     </strong>
      <%= form.text_field :description %>
    </div>


    <div>
<strong>
      <%= form.label :bugg_type, style: "display: block" %>
      </strong>
      <%= form.select :bugg_type, options_for_select([["Bug", 0], ["Feature", 1]])  %>
      
    </div>



    <div>
<strong>
      <%= form.label :status, style: "display: block" %>
</strong>
    <%= form.select :status, options_for_select([["New", 0]])  %>
      
      
      
    </div>
    

    <div>
    <strong>
    <%= form.label :screenshot, style: "display: block" %>
    </strong>
      <%= form.file_field :screenshot %>
    </div>
    
  
    <div>
  
    <% if @project != nil %>
  
   
  
    <%= form.hidden_field :project_id, value: @project.id %>
  
    <% end %>
  
      <%= form.submit %>
    </div>
  <% end %>
  

<br>



<% if current_user.user_type == 3 %>
<div>
 <%= link_to "See all buggs", buggs_path, class: "btn btn-success" %>
</div>
<% end %> 




</center>

app/views/buggs/show.html.erb
<p style="color: green"><%= notice %></p>

<center>

<% if current_user.user_type == 0 %>
<%= render @bugg %>
 

<% elsif @bugg.qa_id == current_user.id or current_user.user_type == 1 %>

  <%= render @bugg %>
  <% if @bugg.status != 2 %>
    <%= link_to "Edit this bugg", edit_bugg_path(@bugg), class: "btn btn-info" %> 
  <% end %>

  <br>
  <br>

  <% if @bugg.qa_id == current_user.id%>
    <%= button_to "Destroy this bugg", @bugg, method: :delete %>
  <% end %> 

<% else %> 
  <h2> You are unauthorised to see this </h2>
<% end %> 


<div>


  

<% if @bugg.qa_id == current_user.id && current_user.user_type == 3 %>
<%= link_to "See your own bugs", buggs_path, class: "btn btn-primary" %>
<% end %> 

 
  <br>
  <br>

  <%= link_to "Back to Home", projects_path, class: "btn btn-success" %>

</div>

</center>