config/routes.rb
Rails.application.routes.draw do
  resources :buggs
  # get 'bugs/index'
  # get 'bugs/show'
  # get 'bugs/edit'
  # get 'bugs/destroy'
  # get 'bugs/new'

  resources :bugs
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "/sessions#new"

  root :to => redirect("/projects")
  # devise_scope :user do

  #   root :to => "devise/registrations#new"

  # end

  # unauthenticated do
  #   root '/users/sign_up'
  # end

  # authenticated do
  #   root '/projects'
  #   # resources :things
  # end
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_paranoid
  validates :name, presence: true

  belongs_to :user

  has_many :user_projects
  has_many :users, through: :user_projects

  has_many :buggs, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index show edit update destroy]
  load_and_authorize_resource

  # GET /projects or /projects.json
  def index
    if current_user.user_type == 0
      @pagy, @projects = pagy(current_user.projects.with_deleted, page: params[:page], items: 3)
    end
    if current_user.user_type == 1
      @pagy, @projects = pagy(current_user.assigned_projects, page: params[:page], items: 3)
    end
    if current_user.user_type == 2
      @pagy, @projects = pagy(current_user.assigned_projects, page: params[:page], items: 3)
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    print "Test message from projects/show"
    authorize! :read, @project
  rescue CanCan::AccessDenied
    redirect_to projects_path
  end

  # GET /projects/new
  def new
    @project = Project.new
    @manager_check = check_manager
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.create(project_params_new)
    @errorMessage = []
    print('@projec')
    print(@project)
    respond_to do |format|
      if @project.save
        @project.update(project_params)
        format.js
        # format.html {	render :show }
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        print("1111111111111111111111111111111111111111111111111")
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        @project.errors.each do |_key, _value|
          @errorMessage.push
        end
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
        format.js   { render layout: false }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js   { render layout: false }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :user_id, user_ids: [])
  end

  def project_params_new
    params.require(:project).permit(:name, :user_id)
  end

  def check_manager
    return current_user.user_type == 0
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<center>


<%= form_with(model: project, local: false, id: "form_id" ) do |form| %>
    <% if project.errors.any? %>
  
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h4 id="helpBlock" class="help-block"></h4>

  <div>
    <%= form.label "Name of your project", style: "display: block" %>
    <%= form.text_field :name %>
  </div>
<br>


<strong> Add developer </strong>

<div class="container row">
    <%= form.collection_select(:user_ids, User.where.not(user_type: 0), :id, :name,{}, {:multiple => true}) %>
  </div>

<br>


<br>

  <div>
  <button id="pro2" onclick> Btn 2</button>
    <%= form.submit "Next", class: "project-btn", id:"pro" %>
  </div>




  
<% end %>


</center> 


<script type="module">

var formData = $('#form_id').serializeArray()

  $("#pro").on("click", function(e){
    e.preventDefault();
    var formData = $('#form_id').serializeArray()
    console.log(formData[1]["value"])
  });

</script>

app/views/projects/_project.html.erb
<div class="container" id="<%= dom_id project %>">

<hr>
  <p>
    <h2>
    <%= project.name %>
    </h2>
  </p>
  <p>


  <strong>Manager:</strong>
  <%= project.user.name  %>
</p>


<strong>Developers:</strong>

<% if project.users.where(user_type:1).count !=0 %> 


<div class = "row">
<% project.users.each do | u | %>
  <div>
    <% if u.user_type == 1 %>
      <%= u.name %>
    <% end %>
  </div>
<% end %>

<% else %> 

<p> No developers have been added to this project </p>

<% end %>

<br>

<strong>QA:</strong>

<% if project.users.where(user_type:2).count !=0 %> 
<div class = "row">
<% project.users.each do | u | %>
  <div> 
    <% if u.user_type == 2 %>
      <%= u.name %>
    <% end %>
  </div>
<% end %>

<% else %> 

<p> No developers have been added to this project </p>

<% end %>


<br><br>




</div>

app/views/projects/create.js.erb
$("#helpBlock").html("");
console.log(@errorMessage)

app/views/projects/destroy.js.erb
$('.delete_project').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
   alert("You are about to delelet the project!");
   console.log("This is from JS")
});

app/views/projects/edit.html.erb
<center>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
<% if current_user.user_type == 1 %>
  <%= link_to "Show this project", @project, :class => "btn btn-primary" %> <br>
<% end %>

  <%= link_to "Back to projects", projects_path %>
</div>


</center>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>
<center background:>
<hr>

<% flash.each do |type, msg| %>

  <div class="container" style="background:#888888" > 

    <%= msg %>
  </div>
<% end %>

<!-- Here the projects are displayed in table -->

<% if current_user.user_type == 0 %>
  <%= link_to "New project", new_project_path, class: "btn btn-primary"%>
  <hr>
  <h1>Projects you have created</h1>


<% elsif current_user.user_type == 1 %>

  <h1>Projects to develop</h1>
  
<% elsif current_user.user_type == 3 %>
<%= link_to "See all bugs", buggs_path, class: "btn btn-primary" %>
<br>
<br>

  <h1>Projects to test</h1>


  <% end %>



<% if @projects.count != 0 %>

  <div class="container" id="projects">
  <table class="table table-light ">
    <% num = 0 %>
    <thead>
    <tr>
      <th scope="col">Sr. no.</th>
      <th scope="col">Name</th>
      <th scope="col">Manager</th>
      <th scope="col">Total Devs</th>
      <th scope="col">Total QA</th>
      <th scope="col">Total Bugs</th>
      
      
    </tr>
    </thead>
    <tbody>

    <% @projects.each do |project| %>
      
    <tr>
      <th scope="row"> <%= num=num+1 %> </th>
      <td>
      <% if project.deleted_at == nil %> 

        <%= link_to project.name, project %>
        <% else %>
        <%= project.name %> 

      <% end %>
      </td>
      <td> <%= project.user.name %> </td>
      <td> <%= project.users.where(user_type:1).count %> </td>
      <td> <%= project.users.where(user_type:2).count %> </td>
      <td> <%= project.bugg_ids.count %> </td>
     
    </tr>

    <% end %>
  
     </tbody>
    </table>

    <center width= "100%" >
    <%== pagy_info(@pagy)%>
    <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 0 %>
    </center> 


  <% else %>
    <p>No projects to show</p>
  <% end %>

</center>

app/views/projects/new.html.erb
<center>
<h1>Step 1: Name Your New Project</h1>

<button class="btn btn-primary" id="button" > THis is a button </button>

<%= render "form", project: @project%>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

<div id="manipulate"> this is to be changed </div>

</center>

<script type="module"  src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script type="module" >

$("#button").on("click", function(){
  document.getElementById("manipulate").style.color = "red";
  console.log("new.html.erb")
  $('#manipulate').html("Hello World. Welcome to Tutlane");
  });

</script>

app/views/projects/show.html.erb
<center>
  <p style="color: green"><%= notice %></p>
  
  
  <% if @project.user_ids.include? current_user.id or @project.user_id == current_user.id %>


   <%= render @project, from: 0 %>

  <div>
    <%= link_to "Back to projects", projects_path, :class => "btn btn-primary" %>
    <br>
    <br>
    <% if current_user.user_type == 0 %>
      <%= link_to "Add or change developers/QA", edit_project_path(@project), class: "btn btn-success" %>
      <br>
      <br>
      
      <%= button_to "Delete this project", @project, method: :delete, data: {confirm: "Are you sure?"}, :remote => true, :class => 'delete_project' %>
      <% end %>
  </div>


  <% if current_user.user_type == 2 %>
    <%= link_to "Add bug to this project", new_bugg_path( project_id: @project.id ), class: "btn btn-success" %>
      <br>
      <br>
  <% end %>

  <hr>

  <% if current_user.user_type == 1 or current_user.user_type ==  0 %>

    <% @buggss =  @project.buggs %>

    <% if @buggss.count != 0 %>
      <h3> Here are all the bugs in this project </h3>
    <% else %>
      <h3> No bugs found in this project yet</h3>
    <% end %>


  <% elsif current_user.user_type ==  2 %>
    <% @buggss =  @project.buggs.where(qa_id: current_user.id) %>
  <br>
    <% if @buggss.count != 0 %>
    <h3> Your created bugs in this project</h3>
    <% else %>
      <h3> You have not created any bugs in this project yet</h3>
    <% end %>
  <% end %>


  <% if current_user.user_type == 1 or current_user.user_type ==  2 or current_user.user_type ==  0  %>

   
    <div class="container" id="projects">
    <table class="table table-light ">
      <% num = 0 %>
      <thead>
      <tr>
        <th scope="col">Sr. no.</th>
        <th scope="col">Title</th>
        <th scope="col">Type</th>
        <th scope="col">Status</th>
        
      </tr>
      </thead>
      <tbody>
      <% @buggss.each do |bugg| %>
      <tr>
        <th scope="row"> <%= num=num+1 %> </th>
        <% if current_user.user_type != 3 %>
          <td> <%= link_to bugg.title, bugg %> </td>
        <% else %>
          <td> <%= bugg.title %> </td>
        <% end %>

        <td>  
      <% if bugg.bugg_type == 0  %>
        Bug
      <% else %>
        Feature
      <% end %>
    </td>

    <td> 
    <% if bugg.status == 0  %>
    New

    <% elsif bugg.status == 1 %>

    Started

    <% else %>
        <% if bugg.bugg_type == 1 %>
          Completed
        <% else %>
          Resolved
        <% end %>

    <% end %>
    </td>
    
       
    </tr>
    
  <% end %>
    
    </tbody>
  </table>





  <% if current_user.user_type == 1  %>
  
  <h3> Your solved bugs in this project</h3>

  
 
  <% @buggss1 = Bugg.where(project_id: @project.id) %>
  <% @buggss = @buggss1.where(solver_id: current_user.id) %>

  <% if @buggss.count != 0 %>
   
    <div class="container" id="projects">
    <table class="table table-light ">
      <% num = 0 %>
      <thead>
      <tr>
        <th scope="col">Sr. no.</th>
        <th scope="col">Title</th>
        <th scope="col">Type</th>
        <th scope="col">Status</th>
        
      </tr>
      </thead>
      <tbody>
      <% @buggss.each do |bugg| %>
      <tr>
        <th scope="row"> <%= num=num+1 %> </th>
        <% if current_user.user_type != 3 %>
          <td> <%= link_to bugg.title, bugg %> </td>
        <% else %>
          <td> <%= bugg.title %> </td>
        <% end %>

        <td>  
      <% if bugg.bugg_type == 0  %>
        Bug
      <% else %>
        Feature
      <% end %>
    </td>

    <td> 
    <% if bugg.status == 0  %>
    New

    <% elsif bugg.status == 1 %>

    Started

    <% else %>
        <% if bugg.bugg_type == 1 %>
          Completed
        <% else %>
          Resolved
        <% end %>

    <% end %>
    </td>
    
       
    </tr>
    
  <% end %>
    
    </tbody>
  </table>


  
<% end %>
<% end %>




  
<% end %>






<% else %>


<%= link_to "Back to projects", projects_path, :class => "btn btn-primary" %>
<br>
<br>
<% controller.redirect_to projects_path %>
<%= flash[:error] = :NotAutorised %>
    <p>You are not authorized to see this project</p>

  <% end %>



</center>