config/routes.rb
Rails.application.routes.draw do
  resources :buggs
  # get 'bugs/index'
  # get 'bugs/show'
  # get 'bugs/edit'
  # get 'bugs/destroy'
  # get 'bugs/new'

  resources :bugs
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "/sessions#new"

  root :to => redirect("/projects")
  # devise_scope :user do

  #   root :to => "devise/registrations#new"

  # end

  # unauthenticated do
  #   root '/users/sign_up'
  # end

  # authenticated do
  #   root '/projects'
  #   # resources :things
  # end
end

app/models/bug.rb
class Bug < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  validates :bug_type, presence: true
  validates :project_id, presence: true
  # mount uploader :image, AvatarUploader

  validates_uniqueness_of :title, scope: :project_id

  belongs_to :project, foreign_key: 'project_id'
  belongs_to :qa, class_name: "User", foreign_key: 'qa_id'
  # belongs_to :dev, class_name: "User", foreign_key: 'dev_id', optional: true
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = current_user.qa_bugs
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def destroy
  end

  def new
    @bug = Bug.new
    @project = Project.find(params[:project_id])

    print :@c_project
    print @project
    print :@c_project
  end

  def create
    print :params
    print params[:project_id]
    # @bug.update(:project_id => @bug.project_id + bug_params[:project_id].to_i)

    @bug = Bug.new(update_params)
    @project = Project.find(project_params[:project_id])
    print @project
    # @project
    # binding.pry
    @bug.projects_id = @project_id
    @bug.qa_id = current_user.id
    # @bug = Bug.new(bug_params)
    if @bug.save
      redirect_to bug_path(@bug)
    else
      render 'index'
    end
  end

  def update
    if @bug.update(update_params)
      redirect_to bug_path(@bug)
    else
      render 'new'
    end
  end

  def bug_params
    params.require(:bug).permit(:title, :description, :bug_type, :deadline, :status, :screenshot, :project_id)
  end

  def project_params
    params.require(:bug).permit(:project_id)
  end

  def update_params
    params.permit(:title, :description, :bug_type, :deadline, :status, :screenshot, :project_id)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<center>
this is id
<%= c_project_id %>

<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

<br>

<div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

<br>

<div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :matriculation_date, :id => "datepicker" %>
  </div>

<br>

<div>
    <%= form.label :screenshot, style: "display: block" %>
    <%= form.text_field :screenshot %>
  </div>

<br>

<div>
    <%= form.label :bug_type, style: "display: block" %>
    <%= form.number_field :title %>
</div>

<br>

<div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
</div>

<br>
  <div>
          
  <%= print :c_project %>
  <%= print c_project_id %>
  <%= print :c_project %>
    
    <%= form.hidden_field :project_id, value: c_project_id  %>
    <%= form.submit %>

  </div>
<% end %>


</center> 

app/views/bugs/_project.html.erb
<div class="container" id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>




  <p>


  <strong>Manager:</strong>
  <%= project.user.name  %>
</p>


<strong>Developers:</strong>

<div class = "row">
<% project.users.each do | u | %>
  <div> 
    <% if u.user_type == 1 %>
      <%= u.name %>
    <% end %>
  </div>
<% end %>

<br><br>

<strong>QA:</strong>

<div class = "row">
<% project.users.each do | u | %>
  <div> 
    <% if u.user_type == 2 %>
      <%= u.name %>
    <% end %>
  </div>
<% end %>


<br><br>




</div>

app/views/bugs/destroy.html.erb
<h1>Bugs#destroy</h1>
<p>Find me in app/views/bugs/destroy.html.erb</p>

app/views/bugs/edit.html.erb
<center>


<h1>Edit your bug</h1>

<br>
<br>
<br>

<% project = @bug %>

<%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
          <% project.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :deadline, style: "display: block" %>
      <%= form.date_field :deadline, :id => "datepicker" %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :screenshot, style: "display: block" %>
      <%= form.file_field :screenshot %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :bug_type, style: "display: block" %>
      <%= form.number_field :bug_type %>
  </div>
  
  <br>
  
  <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.number_field :status %>
  </div>
  
  <br>
    <div>
            
        # <%= @current_project%>

        
      

      <%= form.submit %>
  
    </div>
  <% end %>
  
</center>

app/views/bugs/index.html.erb
<h1>Bugs#index</h1>


<h1>Bugs in this project</h1>

<center>

  <% if @bugs.count != 0 %>

    <div id="projects">
      <% @bugs.each do |project| %>
        <h5> Title </h5>
        <%= project.title %>
        <br>
        <br>
        <h5> description </h5>

        <%= project.description %>
        <br>
        <p>
            <%= @bug %>
          <%= link_to "Show this bug", bug_path(@bug) %>
        </p>
      <% end %>
    </div>

  <% else %>
      <p>No bugs found yet</p>
  <% end %>




  </center>

app/views/bugs/new.html.erb
<h1>Create a bug</h1>




this is current_project
<%= @project %>


<% project = @bug %>

<%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
          <% project.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :deadline, style: "display: block" %>
      <%= form.date_field :deadline, :id => "datepicker" %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :screenshot, style: "display: block" %>
      <%= form.file_field :screenshot %>
    </div>
  
  <br>
  
  <div>
      <%= form.label :bug_type, style: "display: block" %>
      <%= form.number_field :bug_type %>
  </div>
  
  <br>
  
  <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.number_field :status %>
  </div>
  
  <br>
    <div>
            
        # <%= @current_project%>

    <%= form.hidden_field :project_id, value: @project.id %>

        
      

      <%= form.submit %>
  
    </div>
  <% end %>
  

app/views/bugs/show.html.erb
<h1>Bugs#show</h1>


<%= @bug.status %>
<%= @bug.bug_type %>

<div class="container" >
  <p>
    <strong>Name</strong>
    <%= @bug.title %>
  </p>

<p>
  <strong> Description </strong>
  <%= @bug.description  %>
</p>


<p>

<strong> Deadline </strong>
<%= @bug.deadline  %>
</p>

<p>



<p>


<strong> screenshot </strong>
<%= @bug.screenshot  %>
</p>



<br><br>




</div>


<%= link_to "edit this bug", edit_bug_path(@bug) %>